import {
  CREATE_EVENT,
  CREATE_GUEST,
  CREATE_STALL,
  DELETE_EVENT,
  READ_ALL_CATEGORY,
  READ_ALL_EVENT,
  READ_ALL_GUEST,
  READ_ALL_PARTICIPANT,
  READ_ALL_STALL,
  READ_ALL_VENUE,
  READ_EVENT,
  READ_GUEST,
  READ_STALL,
  READ_TICKET,
  READ_TICKET_BY_QR_CODE,
  READ_VENUE,
  UPDATE_EVENT,
  UPDATE_STALL,
} from './permission.const';

export const admin = [
  READ_ALL_CATEGORY,
  CREATE_EVENT,
  READ_ALL_EVENT,
  READ_EVENT,
  UPDATE_EVENT,
  DELETE_EVENT,
  READ_ALL_PARTICIPANT,
  READ_ALL_GUEST,
  READ_ALL_STALL,
  READ_ALL_VENUE,
];

export const eventVendor = [
  CREATE_GUEST,
  READ_ALL_GUEST,
  READ_GUEST,
  READ_ALL_PARTICIPANT,
];

export const supervisor = [CREATE_GUEST, READ_ALL_GUEST, READ_GUEST];

export const attendee = [
  READ_ALL_GUEST,
  READ_ALL_EVENT,
  READ_ALL_STALL,
  READ_STALL,
  READ_ALL_CATEGORY,
  READ_TICKET,
  READ_ALL_VENUE,
];

export const coordinator = [READ_TICKET_BY_QR_CODE];

export const stallVendor = [
  CREATE_STALL,
  READ_ALL_EVENT,
  READ_ALL_STALL,
  READ_STALL,
  UPDATE_STALL,
  READ_ALL_VENUE,
  READ_VENUE,
];
