import {
  CREATE_EVENT,
  CREATE_GUEST,
  CREATE_PARTICIPANT,
  CREATE_STALL,
  CREATE_VENUE,
  DELETE_EVENT,
  READ_ALL_CATEGORY,
  READ_ALL_EVENT,
  READ_ALL_GUEST,
  READ_ALL_PARTICIPANT,
  READ_ALL_STALL,
  READ_ALL_TICKET,
  READ_ALL_VENUE,
  READ_CATEGORY,
  READ_EVENT,
  READ_GUEST,
  READ_STALL,
  READ_TICKET,
  READ_TICKET_BY_QR_CODE,
  READ_VENUE,
  UPDATE_EVENT,
  UPDATE_STALL,
  UPDATE_USER,
  UPDATE_VENUE,
} from './permission.const';

export const admin = [
  READ_ALL_CATEGORY,
  READ_CATEGORY,
  CREATE_EVENT,
  READ_ALL_EVENT,
  READ_EVENT,
  UPDATE_EVENT,
  DELETE_EVENT,
  READ_ALL_PARTICIPANT,
  READ_ALL_GUEST,
  READ_ALL_STALL,
  READ_ALL_VENUE,
  READ_ALL_TICKET,
  UPDATE_STALL,
  UPDATE_USER,
];

export const eventVendor = [
  READ_ALL_CATEGORY,
  CREATE_EVENT,
  READ_ALL_EVENT,
  READ_EVENT,
  UPDATE_EVENT,
  DELETE_EVENT,
  CREATE_GUEST,
  READ_ALL_GUEST,
  READ_GUEST,
  READ_ALL_PARTICIPANT,
  CREATE_VENUE,
  UPDATE_VENUE,
  UPDATE_STALL,
  UPDATE_USER,
];

export const supervisor = [
  CREATE_GUEST,
  READ_ALL_GUEST,
  READ_GUEST,
  UPDATE_USER,
];

export const attendee = [
  CREATE_PARTICIPANT,
  READ_ALL_GUEST,
  READ_ALL_EVENT,
  READ_ALL_STALL,
  READ_STALL,
  READ_ALL_CATEGORY,
  READ_TICKET,
  READ_ALL_VENUE,
  UPDATE_USER,
];

export const coordinator = [READ_TICKET_BY_QR_CODE, UPDATE_USER];

export const stallVendor = [
  CREATE_STALL,
  READ_ALL_EVENT,
  READ_ALL_STALL,
  READ_STALL,
  READ_ALL_VENUE,
  READ_VENUE,
  UPDATE_USER,
];
